/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KataloqIndexRouteImport } from './routes/kataloq.index'
import { Route as KataloqSlugRouteImport } from './routes/kataloq.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataloqIndexRoute = KataloqIndexRouteImport.update({
  id: '/kataloq/',
  path: '/kataloq/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataloqSlugRoute = KataloqSlugRouteImport.update({
  id: '/kataloq/$slug',
  path: '/kataloq/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kataloq/$slug': typeof KataloqSlugRoute
  '/kataloq/': typeof KataloqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kataloq/$slug': typeof KataloqSlugRoute
  '/kataloq': typeof KataloqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kataloq/$slug': typeof KataloqSlugRoute
  '/kataloq/': typeof KataloqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kataloq/$slug' | '/kataloq/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kataloq/$slug' | '/kataloq'
  id: '__root__' | '/' | '/kataloq/$slug' | '/kataloq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KataloqSlugRoute: typeof KataloqSlugRoute
  KataloqIndexRoute: typeof KataloqIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kataloq/': {
      id: '/kataloq/'
      path: '/kataloq'
      fullPath: '/kataloq/'
      preLoaderRoute: typeof KataloqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kataloq/$slug': {
      id: '/kataloq/$slug'
      path: '/kataloq/$slug'
      fullPath: '/kataloq/$slug'
      preLoaderRoute: typeof KataloqSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KataloqSlugRoute: KataloqSlugRoute,
  KataloqIndexRoute: KataloqIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
